import React from 'react';

import {
    FaAnchor,
    FaAndroid,
    FaArrowDown,
    FaArrowLeft,
    FaArrowRight,
    FaBatteryFull,
    FaBed,
    FaBluetooth,
    FaBolt,
    FaBook,
    FaBookmark,
    FaBrush,
    FaCalendarDays,
    FaCamera,
    FaChair,
    FaChargingStation,
    FaCheck,
    FaChevronLeft,
    FaChevronRight,
    FaChurch,
    FaCloud,
    FaCode,
    FaComment,
    FaCompress,
    FaCookie,
    FaCreditCard,
    FaDownload,
    FaEgg,
    FaEject,
    FaExpand,
    FaEye,
    FaEyeSlash,
    FaFacebook,
    FaFilter,
    FaFingerprint,
    FaFireExtinguisher,
    FaFlag,
    FaFolder,
    FaFolderOpen,
    FaForward,
    FaGamepad,
    FaGavel,
    FaGoogle,
    FaHandshake,
    FaHeadphones,
    FaHotel,
    FaImage,
    FaInbox,
    FaInfo,
    FaKey,
    FaKeyboard,
    FaLaptop,
    FaLayerGroup,
    FaLightbulb,
    FaLink,
    FaList,
    FaLock,
    FaLockOpen,
    FaMap,
    FaMoneyBillTrendUp,
    FaPalette,
    FaPause,
    FaPhone,
    FaPlus,
    FaPowerOff,
    FaPrint,
    FaReact,
    FaReceipt,
    FaRegCircleXmark,
    FaRegHeart,
    FaRegLightbulb,
    FaRegNewspaper,
    FaRegStarHalfStroke,
    FaRegTrashCan,
    FaRegUser,
    FaReply,
    FaReplyAll,
    FaRocket,
    FaRoute,
    FaSchool,
    FaShareFromSquare,
    FaShower,
    FaSort,
    FaSquareGithub,
    FaStar,
    FaStop,
    FaStore,
    FaTabletScreenButton,
    FaTag,
    FaTerminal,
    FaTrain,
    FaTransgender,
    FaTv,
    FaUmbrella,
    FaUpload,
    FaUserTie,
    FaVolumeOff,
    FaWallet,
    FaWarehouse,
} from 'react-icons/fa6';

import type { TIconGroupIcons } from '../types';

export const fa6Group: TIconGroupIcons = {
    tv: <FaTv/>,
    box: undefined,
    law: undefined,
    tag: <FaTag/>,
    key: <FaKey/>,
    map: <FaMap/>,
    egg: <FaEgg/>,
    eye: <FaEye/>,
    bed: <FaBed/>,
    user: <FaRegUser/>,
    edit: undefined,
    lamp: <FaRegLightbulb/>,
    plus: <FaPlus/>,
    star: undefined,
    bolt: <FaBolt/>,
    book: <FaBook/>,
    info: <FaInfo/>,
    code: <FaCode/>,
    like: <FaRegHeart/>,
    exit: undefined,
    flag: <FaFlag/>,
    link: <FaLink/>,
    list: <FaList/>,
    lock: <FaLock/>,
    sort: <FaSort/>,
    stop: <FaStop/>,
    home: undefined,
    trash: <FaRegTrashCan/>,
    group: <FaLayerGroup/>,
    brush: <FaBrush/>,
    chair: <FaChair/>,
    check: <FaCheck/>,
    close: <FaRegCircleXmark/>,
    react: <FaReact/>,
    phone: <FaPhone/>,
    cloud: <FaCloud/>,
    hotel: <FaHotel/>,
    image: <FaImage/>,
    inbox: <FaInbox/>,
    gavel: <FaGavel/>,
    eject: <FaEject/>,
    pause: <FaPause/>,
    print: <FaPrint/>,
    store: <FaStore/>,
    reply: <FaReply/>,
    train: <FaTrain/>,
    route: <FaRoute/>,
    share: <FaShareFromSquare/>,
    search: undefined,
    github: <FaSquareGithub/>,
    config: undefined,
    church: <FaChurch/>,
    google: <FaGoogle/>,
    camera: <FaCamera/>,
    anchor: <FaAnchor/>,
    folder: <FaFolder/>,
    expand: <FaExpand/>,
    filter: <FaFilter/>,
    cookie: <FaCookie/>,
    laptop: <FaLaptop/>,
    wallet: <FaWallet/>,
    upload: <FaUpload/>,
    school: <FaSchool/>,
    rocket: <FaRocket/>,
    system: undefined,
    shower: <FaShower/>,
    tablet: <FaTabletScreenButton/>,
    android: <FaAndroid/>,
    forward: <FaForward/>,
    comment: <FaComment/>,
    gamepad: <FaGamepad/>,
    palette: <FaPalette/>,
    receipt: <FaReceipt/>,
    confirm: undefined,
    warning: undefined,
    expense: <FaMoneyBillTrendUp/>,
    category: undefined,
    'user-tie': <FaUserTie/>,
    'arrow-up': undefined,
    facebook: <FaFacebook/>,
    calendar: <FaCalendarDays/>,
    document: undefined,
    bookmark: <FaBookmark/>,
    compress: <FaCompress/>,
    terminal: <FaTerminal/>,
    download: <FaDownload/>,
    keyboard: <FaKeyboard/>,
    umbrella: <FaUmbrella/>,
    'sign-in': undefined,
    'sign-out': undefined,
    warehouse: <FaWarehouse/>,
    lightbulb: <FaLightbulb/>,
    'lock-open': <FaLockOpen/>,
    handshake: <FaHandshake/>,
    'power-off': <FaPowerOff/>,
    'reply-all': <FaReplyAll/>,
    newspaper: <FaRegNewspaper/>,
    'star-half': <FaRegStarHalfStroke/>,
    bluetooth: <FaBluetooth/>,
    dashboard: undefined,
    hamburger: undefined,
    'eye-close': <FaEyeSlash/>,
    'arrow-down': <FaArrowDown/>,
    'arrow-left': <FaArrowLeft/>,
    headphones: <FaHeadphones/>,
    'volume-off': <FaVolumeOff/>,
    transgender: <FaTransgender/>,
    'folder-open': <FaFolderOpen/>,
    'credit-card': <FaCreditCard/>,
    fingerprint: <FaFingerprint/>,
    'arrow-right': <FaArrowRight/>,
    'battery-full': <FaBatteryFull/>,
    'star-filled': <FaStar/>,
    'chevron-up': undefined,
    'chevron-left': <FaChevronLeft/>,
    'chevron-down': undefined,
    'chevron-right': <FaChevronRight/>,
    'arrow-up-outline': undefined,
    'charging-station': <FaChargingStation/>,
    'arrow-down-outline': undefined,
    'fire-extinguisher': <FaFireExtinguisher/>,
};