import {
    MdAllInbox,
    MdAnchor,
    MdAndroid,
    MdBatteryFull,
    MdBluetoothSearching,
    MdBookmark,
    MdBrush,
    MdCalendarMonth,
    MdCameraAlt,
    MdCategory,
    MdChairAlt,
    MdChargingStation,
    MdCheck,
    MdCheckCircle,
    MdChecklist,
    MdChurch,
    MdClose,
    MdCloseFullscreen,
    MdCloud,
    MdCloudDownload,
    MdCloudUpload,
    MdComment,
    MdCookie,
    MdCreditCard,
    MdEdit,
    MdEditDocument,
    MdEgg,
    MdEject,
    MdExitToApp,
    MdFacebook,
    MdFastForward,
    MdFingerprint,
    MdFireExtinguisher,
    MdFlag,
    MdFolder,
    MdFolderOpen,
    MdFullscreen,
    MdGavel,
    MdHeadphones,
    MdHotel,
    MdImage,
    MdKeyboard,
    MdLaptop,
    MdLightbulb,
    MdLightbulbOutline,
    MdLink,
    MdLocalPhone,
    MdLocalPrintshop,
    MdLockOpen,
    MdLockOutline,
    MdMap,
    MdNewspaper,
    MdOutlineArrowBack,
    MdOutlineArrowDropDown,
    MdOutlineArrowDropUp,
    MdOutlineArrowForward,
    MdOutlineFilterList,
    MdOutlineHandshake,
    MdOutlineInfo,
    MdOutlineKey,
    MdOutlineKeyboardArrowDown,
    MdOutlineKeyboardArrowLeft,
    MdOutlineKeyboardArrowRight,
    MdOutlineKeyboardArrowUp,
    MdOutlinePauseCircle,
    MdOutlinePowerSettingsNew,
    MdOutlineReceiptLong,
    MdOutlineReply,
    MdOutlineReplyAll,
    MdOutlineRocketLaunch,
    MdOutlineRoute,
    MdOutlineShare,
    MdOutlineShower,
    MdOutlineSortByAlpha,
    MdOutlineSpaceDashboard,
    MdOutlineStopCircle,
    MdOutlineStore,
    MdOutlineTabletAndroid,
    MdOutlineTrain,
    MdOutlineTransgender,
    MdOutlineUmbrella,
    MdOutlineVolumeOff,
    MdOutlineWarehouse,
    MdOutlineWarningAmber,
    MdPalette,
    MdPerson,
    MdSchool, MdSearch,
    MdSingleBed,
    MdTerminal,
    MdTv,
    MdVideogameAsset,
    MdWallet,
} from 'react-icons/md';

import type { TIconGroupIcons } from '../types';

export const mdGroup: TIconGroupIcons = {
    tv: <MdTv />,
    box: undefined,
    law: undefined,
    tag: undefined,
    key: <MdOutlineKey />,
    map: <MdMap />,
    egg: <MdEgg />,
    eye: undefined,
    bed: <MdSingleBed />,
    user: <MdPerson />,
    edit: <MdEdit />,
    lamp: <MdLightbulb />,
    plus: undefined,
    star: undefined,
    bolt: undefined,
    book: undefined,
    info: <MdOutlineInfo />,
    code: undefined,
    like: undefined,
    exit: <MdExitToApp />,
    flag: <MdFlag />,
    link: <MdLink />,
    list: <MdChecklist />,
    lock: <MdLockOutline />,
    sort: <MdOutlineSortByAlpha />,
    stop: <MdOutlineStopCircle />,
    home: undefined,
    trash: undefined,
    group: undefined,
    brush: <MdBrush />,
    chair: <MdChairAlt />,
    check: <MdCheck />,
    close: <MdClose />,
    react: undefined,
    phone: <MdLocalPhone />,
    cloud: <MdCloud />,
    hotel: <MdHotel />,
    image: <MdImage />,
    inbox: <MdAllInbox />,
    gavel: <MdGavel />,
    eject: <MdEject />,
    pause: <MdOutlinePauseCircle />,
    print: <MdLocalPrintshop />,
    store: <MdOutlineStore />,
    reply: <MdOutlineReply />,
    train: <MdOutlineTrain />,
    route: <MdOutlineRoute />,
    share: <MdOutlineShare />,
    search: <MdSearch />,
    github: undefined,
    config: undefined,
    church: <MdChurch />,
    google: undefined,
    camera: <MdCameraAlt />,
    anchor: <MdAnchor />,
    folder: <MdFolder />,
    expand: <MdFullscreen />,
    filter: <MdOutlineFilterList />,
    cookie: <MdCookie />,
    laptop: <MdLaptop />,
    wallet: <MdWallet />,
    upload: <MdCloudUpload />,
    school: <MdSchool />,
    rocket: <MdOutlineRocketLaunch />,
    system: undefined,
    shower: <MdOutlineShower />,
    tablet: <MdOutlineTabletAndroid />,
    android: <MdAndroid />,
    forward: <MdFastForward />,
    comment: <MdComment />,
    gamepad: <MdVideogameAsset />,
    palette: <MdPalette />,
    receipt: <MdOutlineReceiptLong />,
    confirm: <MdCheckCircle />,
    warning: <MdOutlineWarningAmber />,
    expense: undefined,
    'user-tie': undefined,
    category: <MdCategory />,
    'arrow-up': <MdOutlineArrowDropUp />,
    facebook: <MdFacebook />,
    calendar: <MdCalendarMonth />,
    document: <MdEditDocument />,
    bookmark: <MdBookmark />,
    compress: <MdCloseFullscreen />,
    terminal: <MdTerminal />,
    download: <MdCloudDownload />,
    keyboard: <MdKeyboard />,
    umbrella: <MdOutlineUmbrella />,
    'sign-in': undefined,
    'sign-out': undefined,
    warehouse: <MdOutlineWarehouse />,
    lightbulb: <MdLightbulbOutline />,
    'lock-open': <MdLockOpen />,
    handshake: <MdOutlineHandshake />,
    'power-off': <MdOutlinePowerSettingsNew />,
    'reply-all': <MdOutlineReplyAll />,
    newspaper: <MdNewspaper />,
    'star-half': undefined,
    bluetooth: <MdBluetoothSearching />,
    dashboard: <MdOutlineSpaceDashboard />,
    hamburger: undefined,
    'eye-close': undefined,
    'arrow-down': <MdOutlineArrowDropDown />,
    'arrow-left': <MdOutlineArrowBack />,
    headphones: <MdHeadphones />,
    'volume-off': <MdOutlineVolumeOff />,
    transgender: <MdOutlineTransgender />,
    'folder-open': <MdFolderOpen />,
    'credit-card': <MdCreditCard />,
    fingerprint: <MdFingerprint />,
    'arrow-right': <MdOutlineArrowForward />,
    'battery-full': <MdBatteryFull />,
    'star-filled': undefined,
    'chevron-up': undefined,
    'chevron-left': <MdOutlineKeyboardArrowLeft />,
    'chevron-down': undefined,
    'chevron-right': <MdOutlineKeyboardArrowRight />,
    'arrow-up-outline': <MdOutlineKeyboardArrowUp />,
    'charging-station': <MdChargingStation />,
    'arrow-down-outline': <MdOutlineKeyboardArrowDown />,
    'fire-extinguisher': <MdFireExtinguisher />,
};