import React from 'react';

import {
  CiCalendar,
  CiCamera,
  CiEdit,
  CiHeart,
  CiPhone,
  CiStar,
  CiUser,
  CiWarning,
} from 'react-icons/ci';

import type { TIconGroupIcons } from '../types';

export const ciGroup: TIconGroupIcons = {
  tv: undefined,
  box: undefined,
  tag: undefined,
  key: undefined,
  map: undefined,
  egg: undefined,
  eye: undefined,
  bed: undefined,
  user: <CiUser />,
  edit: <CiEdit />,
  lamp: undefined,
  star: <CiStar />,
  bolt: undefined,
  book: undefined,
  info: undefined,
  code: undefined,
  like: <CiHeart />,
  exit: undefined,
  flag: undefined,
  link: undefined,
  list: undefined,
  lock: undefined,
  sort: undefined,
  stop: undefined,
  home: undefined,
  trash: undefined,
  group: undefined,
  brush: undefined,
  chair: undefined,
  check: undefined,
  close: undefined,
  react: undefined,
  phone: <CiPhone />,
  cloud: undefined,
  hotel: undefined,
  image: undefined,
  inbox: undefined,
  gavel: undefined,
  eject: undefined,
  pause: undefined,
  print: undefined,
  store: undefined,
  reply: undefined,
  train: undefined,
  route: undefined,
  share: undefined,
  config: undefined,
  church: undefined,
  google: undefined,
  camera: <CiCamera />,
  anchor: undefined,
  folder: undefined,
  expand: undefined,
  filter: undefined,
  cookie: undefined,
  laptop: undefined,
  wallet: undefined,
  upload: undefined,
  school: undefined,
  rocket: undefined,
  shower: undefined,
  tablet: undefined,
  android: undefined,
  forward: undefined,
  comment: undefined,
  gamepad: undefined,
  palette: undefined,
  receipt: undefined,
  confirm: undefined,
  warning: <CiWarning />,
  expense: undefined,
  category: undefined,
  'user-tie': undefined,
  'arrow-up': undefined,
  facebook: undefined,
  calendar: <CiCalendar />,
  document: undefined,
  bookmark: undefined,
  compress: undefined,
  terminal: undefined,
  download: undefined,
  keyboard: undefined,
  umbrella: undefined,
  'sign-in': undefined,
  'sign-out': undefined,
  warehouse: undefined,
  lightbulb: undefined,
  'lock-open': undefined,
  handshake: undefined,
  'power-off': undefined,
  'reply-all': undefined,
  newspaper: undefined,
  'star-half': undefined,
  bluetooth: undefined,
  dashboard: undefined,
  hamburger: undefined,
  'eye-close': undefined,
  'arrow-down': undefined,
  'arrow-left': undefined,
  headphones: undefined,
  'volume-off': undefined,
  transgender: undefined,
  'folder-open': undefined,
  'credit-card': undefined,
  fingerprint: undefined,
  'arrow-right': undefined,
  'battery-full': undefined,
  'star-filled': undefined,
  'chevron-up': undefined,
  'chevron-left': undefined,
  'chevron-down': undefined,
  'chevron-right': undefined,
  'arrow-up-outline': undefined,
  'charging-station': undefined,
  'arrow-down-outline': undefined,
  'fire-extinguisher': undefined,
};