import React from 'react';

import {
  IoIosArrowBack,
  IoIosArrowDown,
  IoIosArrowForward,
  IoIosArrowRoundBack,
  IoIosArrowRoundDown,
  IoIosArrowRoundForward,
  IoIosArrowUp,
  IoIosBatteryFull,
  IoIosBed,
  IoIosBluetooth,
  IoIosBook,
  IoIosBookmark,
  IoIosBulb,
  IoIosCamera,
  IoIosCard,
  IoIosChatboxes,
  IoIosCheckmark,
  IoIosCheckmarkCircleOutline,
  IoIosClose,
  IoIosCloud,
  IoIosCode,
  IoIosColorPalette,
  IoIosEgg,
  IoIosExpand,
  IoIosFlag,
  IoIosFlash,
  IoIosFolder,
  IoIosFolderOpen,
  IoIosHeartEmpty,
  IoIosImage,
  IoIosInformation,
  IoIosKey,
  IoIosLaptop,
  IoIosLink,
  IoIosList,
  IoIosLock,
  IoIosPause,
  IoIosPerson,
  IoIosPhonePortrait,
  IoIosPower,
  IoIosPricetag,
  IoIosRocket,
  IoIosSchool,
  IoIosShareAlt,
  IoIosStar,
  IoIosStarHalf,
  IoIosStarOutline,
  IoIosTabletPortrait,
  IoIosTrain,
  IoIosTrash,
  IoIosUmbrella,
  IoIosUnlock,
  IoIosVolumeOff,
  IoIosWallet,
  IoIosWarning,
  IoLogoAndroid,
  IoLogoFacebook,
  IoLogoGameControllerA,
  IoLogoGithub,
  IoLogoGoogle,
  IoMdAppstore,
  IoMdBatteryCharging,
  IoMdBrush,
  IoMdCalendar,
  IoMdCloudDownload,
  IoMdCloudUpload,
  IoMdContract,
  IoMdDocument,
  IoMdExit,
  IoMdEye,
  IoMdEyeOff,
  IoMdFastforward,
  IoMdFingerPrint,
  IoMdHeadset,
  IoMdMap,
  IoMdPrint,
  IoMdTransgender,
  IoMdTv,
} from 'react-icons/io';

import type { TIconGroupIcons } from '../types';

export const ioGroup: TIconGroupIcons = {
  tv: <IoMdTv/>,
  box: undefined,
  law: undefined,
  tag: <IoIosPricetag/>,
  key: <IoIosKey/>,
  map: <IoMdMap/>,
  egg: <IoIosEgg/>,
  eye: <IoMdEye/>,
  bed: <IoIosBed/>,
  user: <IoIosPerson/>,
  edit: undefined,
  lamp: <IoIosBulb/>,
  plus: undefined,
  star: <IoIosStarOutline/>,
  bolt: <IoIosFlash/>,
  book: <IoIosBook/>,
  info: <IoIosInformation/>,
  code: <IoIosCode/>,
  like: <IoIosHeartEmpty/>,
  exit: <IoMdExit/>,
  flag: <IoIosFlag/>,
  link: <IoIosLink/>,
  list: <IoIosList/>,
  lock: <IoIosLock/>,
  sort: undefined,
  stop: undefined,
  home: undefined,
  trash: <IoIosTrash/>,
  group: undefined,
  brush: <IoMdBrush/>,
  chair: undefined,
  check: <IoIosCheckmark/>,
  close: <IoIosClose/>,
  react: undefined,
  phone: <IoIosPhonePortrait/>,
  cloud: <IoIosCloud/>,
  hotel: undefined,
  image: <IoIosImage/>,
  inbox: undefined,
  gavel: undefined,
  eject: undefined,
  pause: <IoIosPause/>,
  print: <IoMdPrint/>,
  store: <IoMdAppstore/>,
  reply: undefined,
  train: <IoIosTrain/>,
  route: undefined,
  share: <IoIosShareAlt/>,
  github: <IoLogoGithub/>,
  config: undefined,
  church: undefined,
  google: <IoLogoGoogle/>,
  camera: <IoIosCamera/>,
  anchor: undefined,
  folder: <IoIosFolder/>,
  expand: <IoIosExpand/>,
  filter: undefined,
  cookie: undefined,
  laptop: <IoIosLaptop/>,
  wallet: <IoIosWallet/>,
  upload: <IoMdCloudUpload/>,
  school: <IoIosSchool/>,
  rocket: <IoIosRocket/>,
  system: undefined,
  shower: undefined,
  tablet: <IoIosTabletPortrait/>,
  android: <IoLogoAndroid/>,
  forward: <IoMdFastforward/>,
  comment: <IoIosChatboxes/>,
  gamepad: <IoLogoGameControllerA/>,
  palette: <IoIosColorPalette/>,
  receipt: undefined,
  confirm: <IoIosCheckmarkCircleOutline/>,
  warning: <IoIosWarning/>,
  expense: undefined,
  category: undefined,
  'user-tie': undefined,
  'arrow-up': undefined,
  facebook: <IoLogoFacebook/>,
  calendar: <IoMdCalendar/>,
  document: <IoMdDocument/>,
  bookmark: <IoIosBookmark/>,
  compress: <IoMdContract/>,
  terminal: undefined,
  download: <IoMdCloudDownload/>,
  keyboard: undefined,
  umbrella: <IoIosUmbrella/>,
  'sign-in': undefined,
  'sign-out': undefined,
  warehouse: undefined,
  lightbulb: <IoIosBulb/>,
  'lock-open': <IoIosUnlock/>,
  handshake: undefined,
  'power-off': <IoIosPower/>,
  'reply-all': undefined,
  newspaper: undefined,
  'star-half': <IoIosStarHalf/>,
  bluetooth: <IoIosBluetooth/>,
  dashboard: undefined,
  hamburger: undefined,
  'eye-close': <IoMdEyeOff/>,
  'arrow-down': <IoIosArrowRoundDown/>,
  'arrow-left': <IoIosArrowRoundBack/>,
  headphones: <IoMdHeadset/>,
  'volume-off': <IoIosVolumeOff/>,
  transgender: <IoMdTransgender/>,
  'folder-open': <IoIosFolderOpen/>,
  'credit-card': <IoIosCard/>,
  fingerprint: <IoMdFingerPrint/>,
  'arrow-right': <IoIosArrowRoundForward/>,
  'battery-full': <IoIosBatteryFull/>,
  'star-filled': <IoIosStar/>,
  'chevron-up': undefined,
  'chevron-left': <IoIosArrowBack/>,
  'chevron-down': undefined,
  'chevron-right': <IoIosArrowForward/>,
  'arrow-up-outline': <IoIosArrowUp/>,
  'charging-station': <IoMdBatteryCharging/>,
  'arrow-down-outline': <IoIosArrowDown/>,
  'fire-extinguisher': undefined,
};