import {
  IoArrowBack,
  IoArrowBackOutline,
  IoArrowDown,
  IoArrowDownOutline,
  IoArrowForward,
  IoArrowUp,
  IoBatteryCharging,
  IoBatteryFull,
  IoBed,
  IoBluetooth,
  IoBook,
  IoBookmark,
  IoBrush,
  IoBulb,
  IoCalendar,
  IoCamera,
  IoCard,
  IoChatbox,
  IoCheckmark,
  IoCheckmarkCircleOutline,
  IoClose,
  IoCloud,
  IoCloudDownload,
  IoCloudUpload,
  IoCode,
  IoColorPalette,
  IoContract,
  IoDocumentTextOutline,
  IoEgg,
  IoExit,
  IoExpand,
  IoEye,
  IoEyeOff,
  IoFingerPrint,
  IoFlag,
  IoFlash,
  IoFolder,
  IoFolderOpen,
  IoGameController,
  IoHeadset,
  IoHeartOutline,
  IoImage,
  IoInformation,
  IoKey,
  IoLaptop,
  IoLink,
  IoList,
  IoLockClosed,
  IoLockOpen,
  IoLogoAndroid,
  IoLogoFacebook,
  IoLogoGithub,
  IoLogoGoogle,
  IoMap,
  IoPause,
  IoPerson,
  IoPhonePortrait,
  IoPlayForwardCircle,
  IoPower,
  IoPricetag,
  IoPrint,
  IoRocket,
  IoSchool,
  IoShareSocialOutline,
  IoStar,
  IoStarHalf,
  IoStarOutline,
  IoStorefront,
  IoTabletPortrait,
  IoTrain,
  IoTransgender,
  IoTrash,
  IoTv,
  IoUmbrella,
  IoVolumeOff,
  IoWallet,
  IoWarning,
} from 'react-icons/io5';

import type { TIconGroupIcons } from '../types';

import React from 'react';

export const io5Group: TIconGroupIcons = {
  tv: <IoTv/>,
  box: undefined,
  tag: <IoPricetag/>,
  key: <IoKey/>,
  map: <IoMap/>,
  egg: <IoEgg/>,
  eye: <IoEye/>,
  bed: <IoBed/>,
  edit: undefined,
  user: <IoPerson/>,
  lamp: <IoBulb/>,
  star: <IoStarOutline/>,
  bolt: <IoFlash/>,
  book: <IoBook/>,
  info: <IoInformation/>,
  code: <IoCode/>,
  like: <IoHeartOutline/>,
  exit: <IoExit/>,
  flag: <IoFlag/>,
  link: <IoLink/>,
  list: <IoList/>,
  lock: <IoLockClosed/>,
  sort: undefined,
  stop: undefined,
  home: undefined,
  trash: <IoTrash/>,
  group: undefined,
  brush: <IoBrush/>,
  chair: undefined,
  check: <IoCheckmark/>,
  close: <IoClose/>,
  react: undefined,
  phone: <IoPhonePortrait/>,
  cloud: <IoCloud/>,
  hotel: undefined,
  image: <IoImage/>,
  inbox: undefined,
  gavel: undefined,
  eject: undefined,
  pause: <IoPause/>,
  print: <IoPrint/>,
  store: <IoStorefront/>,
  reply: undefined,
  train: <IoTrain/>,
  route: undefined,
  share: <IoShareSocialOutline/>,
  github: <IoLogoGithub/>,
  config: undefined,
  church: undefined,
  google: <IoLogoGoogle/>,
  camera: <IoCamera/>,
  anchor: undefined,
  folder: <IoFolder/>,
  expand: <IoExpand/>,
  filter: undefined,
  cookie: undefined,
  laptop: <IoLaptop/>,
  wallet: <IoWallet/>,
  upload: <IoCloudUpload/>,
  school: <IoSchool/>,
  rocket: <IoRocket/>,
  shower: undefined,
  tablet: <IoTabletPortrait/>,
  android: <IoLogoAndroid/>,
  forward: <IoPlayForwardCircle/>,
  comment: <IoChatbox/>,
  gamepad: <IoGameController/>,
  palette: <IoColorPalette/>,
  receipt: undefined,
  confirm: <IoCheckmarkCircleOutline/>,
  warning: <IoWarning/>,
  expense: undefined,
  category: undefined,
  'user-tie': undefined,
  'arrow-up': undefined,
  facebook: <IoLogoFacebook/>,
  calendar: <IoCalendar/>,
  document: <IoDocumentTextOutline/>,
  bookmark: <IoBookmark/>,
  compress: <IoContract/>,
  terminal: undefined,
  download: <IoCloudDownload/>,
  keyboard: undefined,
  umbrella: <IoUmbrella/>,
  'sign-in': undefined,
  'sign-out': undefined,
  warehouse: undefined,
  lightbulb: <IoBulb/>,
  'lock-open': <IoLockOpen/>,
  handshake: undefined,
  'power-off': <IoPower/>,
  'reply-all': undefined,
  newspaper: undefined,
  'star-half': <IoStarHalf/>,
  bluetooth: <IoBluetooth/>,
  dashboard: undefined,
  hamburger: undefined,
  'eye-close': <IoEyeOff/>,
  'arrow-down': <IoArrowDownOutline/>,
  'arrow-left': <IoArrowBackOutline/>,
  headphones: <IoHeadset/>,
  'volume-off': <IoVolumeOff/>,
  transgender: <IoTransgender/>,
  'folder-open': <IoFolderOpen/>,
  'credit-card': <IoCard/>,
  fingerprint: <IoFingerPrint/>,
  'arrow-right': <IoArrowForward/>,
  'battery-full': <IoBatteryFull/>,
  'star-filled': <IoStar/>,
  'chevron-up': undefined,
  'chevron-left': <IoArrowBack/>,
  'chevron-down': undefined,
  'chevron-right': <IoArrowForward/>,
  'arrow-up-outline': <IoArrowUp/>,
  'charging-station': <IoBatteryCharging/>,
  'arrow-down-outline': <IoArrowDown/>,
  'fire-extinguisher': undefined,
};